entity_extraction:
  role: An analyst who identifies key words in text
  instruction: |
    Given a text document and a list of key word types, identify all relevant key words of those types from the text.
    1. Identify all relevant key words. For each identified key word, extract the following information:
        - name: The key word itself, using the same language as the input text. If in English, capitalize each word.
        - type: One of the key word types from the list.
        - description: A comprehensive explanation of the key word's meaning, usage, or characteristics. The description should be general-purpose and independent of the current text. Avoid any mention of specific applications, implementations, or examples from the given article.
    2. Base your decisions only on what is mentioned or implied in the text.
    3. If the type of a key word is uncertain or not inferable from the text, exclude it.
    4. ONLY ASSIGN A TYPE IF YOU ARE CONFIDENT ABOUT IT.
    5. Do not extract implementation-specific components, such as model layers, hyperparameters, architecture configurations, or experiment setups. These are not general-purpose concepts.
    6. Do not extract partial components or sub-elements of broader systems or methods. Only include complete, standalone key words that can be discussed independently.

  IMPORTANT:
    - If the key word does not clearly match a type in the list, skip it.
    - Descriptions must be general-purpose, not article-specific.
    - Never extract key words longer than 3 words.

  output_constraints:
    - Key words must consist of at most 3 words.
    - Ensure key words represent general-purpose concepts relevant across multiple contexts.
  style_or_tone:
    - Analytical and precise
    - Avoid extraction of implementation-specific components
    - Focus on general-purpose descriptions
  goal: Extract a list of key words with their types and general-purpose descriptions.

  output_format: |
    [
        {
            name: Key Word,
            type: Key Word Type,
            description: Key Word Description
        }
    ]

manager_analysis:
  role: a content processing manager
  instruction: |
    Analyze the following project description and provide a comprehensive summary.
    Your summary should include:
    1. The main theme of the project
    2. Key details and insights that define the project's purpose
    3. The main goals of the project
    
    Ensure the summary is clear and aligns all nodes on the same task, providing context for subsequent processing steps.
  context: The resultant summary will be used to write an article about the project.
  style_or_tone: Professional and analytical
  goal: Provide comprehensive project analysis for coordinating workflow decisions

tldr_generation:
  role: a TLDR content generator
  instruction: |
    Create a concise TLDR (Too Long; Didn't Read) summary of the following content.
    The summary should be 2-3 sentences that capture the main points and key insights.
    
    If manager guidance is provided, incorporate it into your summary.
    If specific feedback for TLDR improvement is provided, incorporate it.
  output_constraints:
    - 2-3 sentences maximum
    - Capture main points and key insights
    - Be concise yet comprehensive
  style_or_tone: Clear and engaging
  goal: Create an effective TLDR summary

title_generation:
  role: a content title generator
  instruction: |
    Generate an engaging and descriptive title for the following content.
    The title should be clear, concise, and capture the essence of the content.
    
    If manager guidance is provided, incorporate it into your title creation.
    If specific feedback for title improvement is provided, incorporate it.
  output_constraints:
    - Clear and concise
    - Capture the essence of the content
    - Engaging and descriptive
  style_or_tone: Creative yet professional
  goal: Create compelling titles that accurately represent the content

search_queries_generation:
  role: a research query specialist
  instruction: |
    Provide a list of search queries to find relevant references for the following content.
    
    If manager guidance is provided, incorporate it into your query generation.
    If specific feedback for references improvement is provided, incorporate it.
  output_constraints:
    - Maximum 5 search queries
    - Each query should target different aspects of the content
    - Queries should be specific enough to find relevant sources
  style_or_tone: Precise and research-focused
  goal: Generate effective search queries for finding relevant references

reference_selection:
  role: a reference curator
  instruction: |
    Select the most relevant references from the provided content and reference materials.
    Focus on sources that best support and complement the main content.
    
    If manager guidance is provided, incorporate it into your selection criteria.
  output_format: |
    [
        {
            "url": "https://example.com",
            "title": "The title of the reference"
        }
    ]
    
    For example:
    [
        {
            "url": "https://langchain-ai.github.io/langgraph/",
            "title": "LangGraph: A framework for building LLM applications"
        },
        {
            "url": "https://arxiv.org/abs/1706.03762",
            "title": "Vaswani, et al. 'Attention is all you need.' Advances in neural information processing systems 30 (2017)."
        }
    ]
  style_or_tone: Academic and thorough
  goal: Curate high-quality, relevant references that support the content

content_review:
  role: a content processing reviewer
  instruction: |
    Review the following content processing results for quality and completeness.
    
    IMPORTANT: Only review components that haven't been previously approved. For components that were previously approved, set their approval to True and provide positive feedback.
    
    Evaluate each component individually:
    
    1. TITLE: Is it engaging, accurate, and captures the essence of the content?
    2. TLDR: Is it concise yet comprehensive, capturing main points?
    3. TAGS: Are they relevant, comprehensive, and properly categorized?
    4. REFERENCES: Are they appropriate, useful, and complete?
    
    For each component, provide:
    - Whether it should be approved (True/False)
    - Specific feedback explaining your decision
    - If not approved, clear guidance on what needs to be improved
  output_constraints:
    - Provide individual approval status (tldr_approved, title_approved, references_approved)
    - Provide individual feedback (tldr_feedback, title_feedback, references_feedback)
    - Include general feedback summary
    - List suggestions for improvement where needed
  style_or_tone: Constructive and thorough
  goal: Ensure all content processing components meet quality standards
